<x-layouts.app title="Tambah Realisasi" active="realizations" :current-client="$currentClient" :user="$user">
<div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div class="mb-3 flex items-center gap-2 text-xs font-medium text-slate-500"><span>Transaksi</span><x-icon name="chevron-right" size="size-3.5"/><span>Realisasi</span><x-icon name="chevron-right" size="size-3.5"/><span class="text-primary-600">Tambah</span></div><h1 class="text-3xl font-semibold tracking-tight text-slate-950">Tambah Realisasi</h1><p class="mt-2 text-sm text-slate-500">Isi data realisasi pekerjaan. Semua field dan assignment karyawan bersifat opsional.</p></div><a href="{{ route('realizations.index') }}" class="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-line bg-white px-4 text-sm font-semibold text-slate-600 shadow-sm transition hover:border-slate-300 hover:bg-slate-50"><x-icon name="chevron-right" class="rotate-180" size="size-4"/> Kembali</a></div>

<form data-realization-form action="{{ route('realizations.store') }}" data-redirect="{{ route('realizations.index') }}" class="grid gap-5"><input type="hidden" name="_method" value="POST">
    <x-card><div class="grid gap-4 sm:grid-cols-2">
        <label class="grid gap-2 text-sm font-semibold"><span>Tanggal borongan</span><input type="text" name="work_date" data-datepicker autocomplete="off" placeholder="Pilih tanggal" class="h-11 rounded-lg border border-line px-3 font-normal"></label>
        <label class="grid gap-2 text-sm font-semibold"><span>Shift</span><select name="shift_id" data-tom-select data-tom-select-remote="{{ route('shifts.options') }}" data-tom-select-placeholder="Pilih shift..." class="h-11 rounded-lg border border-line bg-white px-3 font-normal"><option value="">Pilih shift...</option></select></label>
        <label class="grid gap-2 text-sm font-semibold"><span>Nomor batch</span><select name="batch_id" data-batch-select data-tom-select data-tom-select-remote="{{ route('batches.options') }}" data-tom-select-depends-on="product_id" data-tom-select-depends-on-selector="[data-product-select]" data-tom-select-placeholder="Pilih nomor batch..." class="h-11 rounded-lg border border-line bg-white px-3 font-normal"><option value="">Pilih nomor batch...</option></select></label>
        <label class="grid gap-2 text-sm font-semibold"><span>SKU</span><select name="product_id" data-product-select data-tom-select data-tom-select-remote="{{ route('products.options') }}" data-tom-select-placeholder="Pilih SKU..." class="h-11 rounded-lg border border-line bg-white px-3 font-normal"><option value="">Pilih SKU...</option></select></label>
        <label class="grid gap-2 text-sm font-semibold sm:col-span-2"><span>Nama produk</span><input type="text" data-product-name readonly placeholder="Otomatis terisi berdasarkan SKU" class="h-11 rounded-lg border border-line bg-slate-50 px-3 font-normal text-slate-600"></label>
        <label class="grid gap-2 text-sm font-semibold"><span>Satuan</span><input type="text" data-product-unit readonly placeholder="Otomatis terisi berdasarkan SKU" class="h-11 rounded-lg border border-line bg-slate-50 px-3 font-normal text-slate-600"></label>
        <label class="grid gap-2 text-sm font-semibold"><span>Estimasi output/jam</span><input type="text" data-product-estimate readonly placeholder="Otomatis terisi berdasarkan SKU" class="h-11 rounded-lg border border-line bg-slate-50 px-3 font-normal text-slate-600"></label>
    </div></x-card>

    <x-card><div data-assignment-section>
        <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h3 class="text-sm font-semibold text-slate-900">Assign karyawan (opsional)</h3><p class="mt-1 text-xs text-slate-500">Penugasan dapat diisi sekarang atau setelah data realisasi tersimpan.</p></div><div class="flex gap-2"><select data-assignment-group class="h-10 rounded-lg border border-line bg-white px-3 text-xs"><option value="">Tambah dari group...</option>@foreach($employees->pluck('group')->filter()->unique('id')->sortBy('name') as $group)<option value="{{ $group->id }}">{{ $group->name }} ({{ $employees->where('group_id', $group->id)->count() }} karyawan)</option>@endforeach</select><button type="button" data-assignment-add-group class="inline-flex h-10 items-center gap-1.5 rounded-lg bg-emerald-50 px-3 text-xs font-semibold text-emerald-700 hover:bg-emerald-100"><x-icon name="plus" size="size-4" /> Group</button></div></div>
        <div data-assignment-rows class="mt-3 grid gap-2"><div data-assignment-row class="flex items-center gap-2"><select name="employee_ids[]" data-assignment-employee class="h-10 min-w-0 flex-1 rounded-lg border border-line bg-white px-3 text-sm"><option value="">Pilih karyawan...</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" data-employee-group="{{ $employee->group_id }}">{{ $employee->employee_no }} — {{ $employee->full_name }}</option>@endforeach</select><button type="button" data-assignment-remove class="hidden rounded-lg bg-red-50 p-2 text-red-600 hover:bg-red-100" aria-label="Hapus karyawan"><x-icon name="trash" size="size-4" /></button><button type="button" data-assignment-add class="rounded-lg bg-emerald-50 p-2 text-emerald-700 hover:bg-emerald-100" aria-label="Tambah karyawan"><x-icon name="plus" size="size-4" /></button></div></div>
    </div></x-card>

    <div class="flex justify-end gap-3"><a href="{{ route('realizations.index') }}" class="inline-flex items-center gap-2 rounded-lg border border-red-200 bg-red-50 px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-100"><x-icon name="x-mark" size="size-4" /> Batal</a><button type="submit" class="inline-flex items-center gap-2 rounded-lg bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-primary-700"><x-icon name="check-circle" size="size-4" /> Simpan realisasi</button></div>
</form>
</x-layouts.app>
