<x-layouts.app title="{{ $canEditMasterData ? 'Edit Realisasi' : 'Edit Hasil Realisasi' }}" active="realizations" :current-client="$currentClient" :user="$user">
    <div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
        <div>
            <div class="mb-3 flex items-center gap-2 text-xs font-medium text-slate-500"><span>Transaksi</span><x-icon name="chevron-right" size="size-3.5"/><span>Realisasi</span><x-icon name="chevron-right" size="size-3.5"/><span class="text-primary-600">Edit</span></div>
            <h1 class="text-3xl font-semibold tracking-tight text-slate-950">{{ $canEditMasterData ? 'Edit Data Realisasi' : 'Edit Hasil Realisasi' }}</h1>
            <p class="mt-2 text-sm text-slate-500">{{ $canEditMasterData ? 'Perubahan data realisasi dapat dilakukan Admin dan Super Admin.' : 'Perbarui hasil pekerjaan yang Anda buat atau kerjakan.' }}</p>
        </div>
        <a href="{{ route('realizations.show', $realization) }}" class="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-line bg-white px-4 text-sm font-semibold text-slate-600 shadow-sm transition hover:border-slate-300 hover:bg-slate-50"><x-icon name="chevron-right" class="rotate-180" size="size-4"/> Kembali</a>
    </div>

    <form method="POST" enctype="multipart/form-data" data-realization-edit-form data-realization-wizard data-wizard-optional="true" action="{{ $canEditMasterData ? route('realizations.admin-update', $realization) : route('realizations.update', $realization) }}" data-redirect="{{ route('realizations.show', $realization) }}" class="grid gap-5">
        <input type="hidden" name="_method" value="PUT">

        <x-card>
            <div class="mb-4">
                <p class="text-xs font-semibold uppercase tracking-wide text-primary-600">Bagian <span data-wizard-current-label>1</span> dari 3</p>
                <h2 class="mt-1 text-lg font-semibold text-slate-900" data-wizard-title tabindex="-1">Produk</h2>
                <p class="mt-1 text-sm text-slate-500" data-wizard-description>Edit informasi produk dan hasil pekerjaan.</p>
            </div>
            <div class="inline-flex max-w-full gap-1 overflow-x-auto rounded-2xl bg-slate-100 p-1.5" role="tablist" aria-label="Bagian form edit realisasi">
                <button id="realization-edit-tab-1" type="button" role="tab" aria-selected="true" aria-controls="realization-edit-panel-1" data-wizard-tab="1" class="inline-flex min-h-11 shrink-0 items-center gap-2 rounded-xl bg-white px-4 py-2 text-sm font-semibold text-primary-700 shadow-sm ring-1 ring-primary-100 transition-all duration-200 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-600"><span data-wizard-tab-icon class="grid size-8 place-items-center rounded-lg bg-primary-50 text-primary-600"><x-icon name="cube" size="size-4" /></span>Produk</button>
                <button id="realization-edit-tab-2" type="button" role="tab" aria-selected="false" aria-controls="realization-edit-panel-2" data-wizard-tab="2" class="inline-flex min-h-11 shrink-0 items-center gap-2 rounded-xl px-4 py-2 text-sm font-semibold text-slate-600 transition-all duration-200 hover:bg-white/70 hover:text-slate-900 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-600"><span data-wizard-tab-icon class="grid size-8 place-items-center rounded-lg text-slate-500"><x-icon name="photo" size="size-4" /></span>Foto</button>
                <button id="realization-edit-tab-3" type="button" role="tab" aria-selected="false" aria-controls="realization-edit-panel-3" data-wizard-tab="3" class="inline-flex min-h-11 shrink-0 items-center gap-2 rounded-xl px-4 py-2 text-sm font-semibold text-slate-600 transition-all duration-200 hover:bg-white/70 hover:text-slate-900 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-600"><span data-wizard-tab-icon class="grid size-8 place-items-center rounded-lg text-slate-500"><x-icon name="users" size="size-4" /></span>Assign</button>
            </div>
            <p class="mt-3 text-xs text-slate-500">Semua field opsional. Anda bisa berpindah tab kapan saja.</p>
        </x-card>

        <section id="realization-edit-panel-1" data-wizard-step="1" role="tabpanel" aria-labelledby="realization-edit-tab-1" aria-label="Produk" tabindex="0">
            @if($canEditMasterData)
                <x-card><div class="grid gap-4 sm:grid-cols-2">
                    <label class="grid gap-2 text-sm font-semibold"><span>Tanggal borongan</span><input type="text" name="work_date" data-datepicker autocomplete="off" value="{{ $realization->work_date?->format('Y-m-d') }}" placeholder="Pilih tanggal" class="h-11 rounded-lg border border-line px-3 font-normal"></label>
                    <label class="grid gap-2 text-sm font-semibold"><span>Shift</span><select name="shift_id" data-tom-select data-tom-select-remote="{{ route('shifts.options') }}" data-tom-select-placeholder="Pilih shift..." class="h-11 rounded-lg border border-line bg-white px-3 font-normal"><option value="">Pilih shift...</option>@if($realization->shift)<option value="{{ $realization->shift_id }}" selected>{{ $realization->shift->name }}</option>@endif</select></label>
                    <label class="grid gap-2 text-sm font-semibold"><span>Nomor batch</span><input type="text" name="batch_no" value="{{ $realization->batch?->batch_no }}" placeholder="B-yyyymmdd-0001" class="h-11 rounded-lg border border-line px-3 font-normal"><small class="font-normal text-slate-500">Format: B-yyyymmdd-0001</small></label>
                    <label class="grid gap-2 text-sm font-semibold"><span>SKU</span><select name="product_id" data-product-select data-tom-select data-tom-select-remote="{{ route('products.options') }}" data-tom-select-placeholder="Pilih SKU..." class="h-11 rounded-lg border border-line bg-white px-3 font-normal"><option value="">Pilih SKU...</option>@if($realization->product)<option value="{{ $realization->product_id }}" data-product-name="{{ $realization->product->name }}" data-product-unit="{{ $realization->product->unit?->name }}" data-product-estimate="{{ $realization->product->estimated_output_per_hour }}" data-product-rate="{{ $realization->product->employee_rate }}" selected>{{ $realization->product->sku }} — {{ $realization->product->name }}</option>@endif</select></label>
                    <label class="grid gap-2 text-sm font-semibold sm:col-span-2"><span>Nama produk</span><input type="text" data-product-name readonly value="{{ $realization->product_name_snapshot }}" placeholder="Otomatis terisi berdasarkan SKU" class="h-11 rounded-lg border border-line bg-slate-50 px-3 font-normal text-slate-600"></label>
                    <label class="grid gap-2 text-sm font-semibold"><span>Satuan</span><input type="text" data-product-unit readonly value="{{ $realization->unit_name_snapshot }}" placeholder="Otomatis terisi berdasarkan SKU" class="h-11 rounded-lg border border-line bg-slate-50 px-3 font-normal text-slate-600"></label>
                    <label class="grid gap-2 text-sm font-semibold"><span>Estimasi output/jam</span><input type="text" data-product-estimate readonly value="{{ $realization->product?->estimated_output_per_hour }}" placeholder="Otomatis terisi berdasarkan SKU" class="h-11 rounded-lg border border-line bg-slate-50 px-3 font-normal text-slate-600"></label>
                    <label class="grid gap-2 text-sm font-semibold"><span>Total (Karton/Kg)</span><input type="number" step="0.001" min="0" name="total_output" data-total-output-input value="{{ $realization->total_output }}" placeholder="Masukkan total output" class="h-11 rounded-lg border border-line px-3 font-normal"></label>
                    <label class="grid gap-2 text-sm font-semibold"><span>Total harga</span><input type="text" data-total-price-preview readonly value="Rp 0" aria-live="polite" class="h-11 rounded-lg border border-line bg-slate-50 px-3 font-semibold text-slate-700"></label>
                    <label class="grid gap-2 text-sm font-semibold"><span>Waktu pengerjaan (1)</span><input type="time" name="start_time" value="{{ $realization->start_time ? substr($realization->start_time, 0, 5) : '' }}" class="h-11 rounded-lg border border-line px-3 font-normal"></label>
                    <label class="grid gap-2 text-sm font-semibold"><span>Waktu pengerjaan (2)</span><input type="time" name="end_time" value="{{ $realization->end_time ? substr($realization->end_time, 0, 5) : '' }}" class="h-11 rounded-lg border border-line px-3 font-normal"></label>
                    <label class="grid gap-2 text-sm font-semibold sm:col-span-2"><span>Report</span><textarea name="report" rows="4" placeholder="Tambahkan catatan hasil pekerjaan jika diperlukan" class="rounded-lg border border-line px-3 py-2 font-normal">{{ $realization->report }}</textarea></label>
                </div></x-card>
            @else
                <x-card><div class="mb-4"><h2 class="text-base font-semibold text-slate-900">Data realisasi pekerjaan</h2><p class="mt-1 text-sm text-slate-500">Tanggal, shift, batch, dan produk hanya dapat diubah Super Admin.</p></div><dl class="grid gap-x-8 gap-y-4 sm:grid-cols-2"><div><dt class="text-xs text-slate-500">Tanggal borongan</dt><dd class="mt-1 font-semibold text-slate-900">{{ $realization->work_date?->format('d/m/Y') ?? '—' }}</dd></div><div><dt class="text-xs text-slate-500">Produk</dt><dd class="mt-1 font-semibold text-slate-900">{{ $realization->product_name_snapshot ?? '—' }}</dd></div><div><dt class="text-xs text-slate-500">Shift</dt><dd class="mt-1 font-semibold text-slate-900">{{ $realization->shift?->name ?? '—' }}</dd></div><div><dt class="text-xs text-slate-500">Nomor batch</dt><dd class="mt-1 font-semibold text-slate-900">{{ $realization->batch?->batch_no ?? '—' }}</dd></div></dl></x-card>
                <x-card class="mt-5"><div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-2 text-sm font-semibold"><span>Total (Karton/Kg)</span><input type="number" step="0.001" min="0" name="total_output" data-total-output-input value="{{ $realization->total_output }}" class="h-11 rounded-lg border border-line px-3 font-normal"></label><label class="grid gap-2 text-sm font-semibold"><span>Total harga</span><input type="text" data-total-price-preview readonly value="Rp 0" class="h-11 rounded-lg border border-line bg-slate-50 px-3 font-semibold text-slate-700"></label><label class="grid gap-2 text-sm font-semibold"><span>Waktu pengerjaan (1)</span><input type="time" name="start_time" value="{{ $realization->start_time ? substr($realization->start_time, 0, 5) : '' }}" class="h-11 rounded-lg border border-line px-3 font-normal"></label><label class="grid gap-2 text-sm font-semibold"><span>Waktu pengerjaan (2)</span><input type="time" name="end_time" value="{{ $realization->end_time ? substr($realization->end_time, 0, 5) : '' }}" class="h-11 rounded-lg border border-line px-3 font-normal"></label><label class="grid gap-2 text-sm font-semibold sm:col-span-2"><span>Report</span><textarea name="report" rows="4" placeholder="Tambahkan catatan hasil pekerjaan jika diperlukan" class="rounded-lg border border-line px-3 py-2 font-normal">{{ $realization->report }}</textarea></label></div></x-card>
            @endif
        </section>

        <section id="realization-edit-panel-2" data-wizard-step="2" role="tabpanel" aria-labelledby="realization-edit-tab-2" aria-label="Foto" class="hidden" tabindex="0">
            <x-card><div class="mb-4 flex items-start gap-3"><span class="grid size-10 shrink-0 place-items-center rounded-xl bg-primary-50 text-primary-600"><x-icon name="arrow-up-tray" size="size-5" /></span><div><h2 class="text-base font-semibold text-slate-900">Foto hasil pekerjaan</h2><p class="mt-1 text-sm text-slate-500">Upload foto baru bila ingin mengganti foto saat ini.</p></div></div><x-form.file-upload name="result_image" label="Upload foto (opsional)" help="JPG, PNG, atau WEBP. Maksimal 3 MB. Foto lebih besar akan dikompres otomatis." max-size-mb="3" compress /></x-card>
        </section>

        <section id="realization-edit-panel-3" data-wizard-step="3" role="tabpanel" aria-labelledby="realization-edit-tab-3" aria-label="Assign karyawan" class="hidden" tabindex="0">
            @if($canEditMasterData)
                <x-card><div data-assignment-section>
                    <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h3 class="text-sm font-semibold text-slate-900">User realisasi</h3><p class="mt-1 text-xs text-slate-500">Atur karyawan yang ditugaskan pada realisasi ini.</p></div><div class="flex flex-wrap gap-2"><select data-assignment-group data-tom-select data-tom-select-placeholder="Cari group..." class="h-10 w-80 max-w-full rounded-lg border border-line bg-white px-3 text-xs"><option value="">Tambah dari group...</option>@foreach($groups as $group)<option value="{{ $group->id }}">{{ $group->name }} ({{ $employees->where('group_id', $group->id)->count() }} karyawan)</option>@endforeach</select><button type="button" data-assignment-add-group class="inline-flex h-10 items-center gap-1.5 rounded-lg bg-emerald-50 px-3 text-xs font-semibold text-emerald-700 hover:bg-emerald-100"><x-icon name="plus" size="size-4" /> Group</button></div></div>
                    <div data-assignment-rows class="mt-3 grid gap-2">@forelse($realization->employeeAssignments as $assignment)<div data-assignment-row class="flex items-center gap-2"><select name="employee_ids[]" data-assignment-employee class="h-10 min-w-0 flex-1 rounded-lg border border-line bg-white px-3 text-sm"><option value="">Pilih karyawan...</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" data-employee-group="{{ $employee->group_id }}" @selected($employee->id === $assignment->employee_id)>{{ $employee->employee_no }} — {{ $employee->full_name }}</option>@endforeach</select><button type="button" data-assignment-remove class="rounded-lg bg-red-50 p-2 text-red-600 hover:bg-red-100" aria-label="Hapus karyawan"><x-icon name="trash" size="size-4" /></button><button type="button" data-assignment-add class="rounded-lg bg-emerald-50 p-2 text-emerald-700 hover:bg-emerald-100" aria-label="Tambah karyawan"><x-icon name="plus" size="size-4" /></button></div>@empty<div data-assignment-row class="flex items-center gap-2"><select name="employee_ids[]" data-assignment-employee class="h-10 min-w-0 flex-1 rounded-lg border border-line bg-white px-3 text-sm"><option value="">Pilih karyawan...</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" data-employee-group="{{ $employee->group_id }}">{{ $employee->employee_no }} — {{ $employee->full_name }}</option>@endforeach</select><button type="button" data-assignment-remove class="hidden rounded-lg bg-red-50 p-2 text-red-600 hover:bg-red-100" aria-label="Hapus karyawan"><x-icon name="trash" size="size-4" /></button><button type="button" data-assignment-add class="rounded-lg bg-emerald-50 p-2 text-emerald-700 hover:bg-emerald-100" aria-label="Tambah karyawan"><x-icon name="plus" size="size-4" /></button></div>@endforelse</div>
                </div></x-card>
            @else
                <x-card><div><h3 class="text-sm font-semibold text-slate-900">Karyawan yang ditugaskan</h3><p class="mt-1 text-sm text-slate-500">Daftar penugasan hanya dapat diubah Super Admin.</p><div class="mt-4 flex flex-wrap gap-2">@forelse($realization->employeeAssignments as $assignment)<span class="rounded-full bg-slate-100 px-3 py-1.5 text-sm text-slate-700">{{ $assignment->employee?->full_name ?? 'Karyawan' }}</span>@empty<span class="text-sm text-slate-500">Belum ada karyawan yang ditugaskan.</span>@endforelse</div></div></x-card>
            @endif
        </section>

        <div class="flex flex-col-reverse justify-between gap-3 sm:flex-row">
            <a href="{{ route('realizations.show', $realization) }}" class="inline-flex items-center justify-center gap-2 rounded-lg border border-red-200 bg-red-50 px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-100"><x-icon name="x-mark" size="size-4" /> Batal</a>
            <div class="flex justify-end gap-3">
                <button type="button" data-wizard-back class="hidden items-center gap-2 rounded-lg border border-line bg-white px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-50"><x-icon name="chevron-right" class="rotate-180" size="size-4" /> Sebelumnya</button>
                <button type="button" data-wizard-next class="inline-flex items-center gap-2 rounded-lg bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-primary-700">Berikutnya <x-icon name="chevron-right" size="size-4" /></button>
                <button type="submit" data-wizard-submit class="hidden items-center gap-2 rounded-lg bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-primary-700"><x-icon name="check-circle" size="size-4" /> {{ $canEditMasterData ? 'Simpan perubahan' : 'Simpan hasil' }}</button>
            </div>
        </div>
    </form>
</x-layouts.app>
