<x-layouts.app title="Detail Realisasi" active="realizations" :current-client="$currentClient" :user="$user">
<div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div class="mb-3 flex items-center gap-2 text-xs font-medium text-slate-500"><span>Transaksi</span><x-icon name="chevron-right" size="size-3.5"/><span>Realisasi</span><x-icon name="chevron-right" size="size-3.5"/><span class="text-primary-600">Detail</span></div><h1 class="text-3xl font-semibold tracking-tight text-slate-950">Detail Realisasi Pekerjaan</h1><p class="mt-2 text-sm text-slate-500">Ringkasan hasil pekerjaan dan informasi pendukung.</p></div><a href="{{ route('realizations.index') }}" class="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-line bg-white px-4 text-sm font-semibold text-slate-600 shadow-sm transition hover:border-slate-300 hover:bg-slate-50"><x-icon name="chevron-right" class="rotate-180" size="size-4"/> Kembali</a></div>
<div class="mb-5 grid gap-4 sm:grid-cols-3">
    <div class="rounded-xl border border-line bg-white p-5 shadow-sm"><span class="grid size-[42px] shrink-0 place-items-center rounded-[10px] bg-primary-50 text-primary-600"><x-icon name="cube"/></span><p class="mt-4 text-xs font-medium text-slate-500">Total output</p><p class="mt-1 text-2xl font-semibold tracking-tight text-slate-950">{{ $realization->total_output !== null ? number_format($realization->total_output, 3, ',', '.') : '—' }}</p><p class="mt-1 text-xs text-slate-500">{{ $realization->unit_name_snapshot }}</p></div>
    <div class="rounded-xl border border-line bg-white p-5 shadow-sm"><span class="grid size-[42px] shrink-0 place-items-center rounded-[10px] bg-primary-50 text-primary-600"><x-icon name="clock"/></span><p class="mt-4 text-xs font-medium text-slate-500">Tanggal kerja</p><p class="mt-1 text-2xl font-semibold tracking-tight text-slate-950">{{ $realization->work_date?->format('d/m/Y') }}</p><p class="mt-1 text-xs text-slate-500">{{ $realization->shift?->name ?? 'Tanpa shift' }}</p></div>
    <div class="rounded-xl border border-line bg-white p-5 shadow-sm"><span class="grid size-[42px] shrink-0 place-items-center rounded-[10px] bg-primary-50 text-primary-600"><x-icon name="clipboard-document-list"/></span><p class="mt-4 text-xs font-medium text-slate-500">Status</p><div class="mt-2"><x-badge :variant="in_array($realization->status, ['submitted', 'finalized'], true) ? 'success' : 'warning'">{{ match($realization->status) { 'assigned' => 'Ditugaskan', 'submitted' => 'Dikirim', 'finalized' => 'Final', default => ucfirst($realization->status) } }}</x-badge></div></div>
</div>
<div class="grid gap-5 lg:grid-cols-[1.4fr_0.8fr]">
    <x-card><div class="mb-5 flex items-center justify-between"><h2 class="text-base font-semibold text-slate-900">Informasi pekerjaan</h2><span class="rounded-md bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600">{{ $realization->sku_snapshot }}</span></div><dl class="grid gap-x-8 gap-y-5 sm:grid-cols-2"><div><dt class="text-xs text-slate-500">Tanggal borongan</dt><dd class="mt-1.5 font-semibold text-slate-900">{{ $realization->work_date?->format('d/m/Y') ?? '—' }}</dd></div><div><dt class="text-xs text-slate-500">Nomor batch</dt><dd class="mt-1.5 font-semibold text-slate-900">{{ $realization->batch?->batch_no ?? '—' }}</dd></div><div><dt class="text-xs text-slate-500">Nama produk</dt><dd class="mt-1.5 font-semibold text-slate-900">{{ $realization->product_name_snapshot }}</dd></div><div><dt class="text-xs text-slate-500">Shift</dt><dd class="mt-1.5 font-semibold text-slate-900">{{ $realization->shift?->name ?? '—' }}</dd></div><div><dt class="text-xs text-slate-500">Waktu pengerjaan</dt><dd class="mt-1.5 font-semibold text-slate-900">{{ $realization->start_time ? substr($realization->start_time, 0, 5) : 'Belum diisi' }}{{ $realization->end_time ? ' – '.substr($realization->end_time, 0, 5) : '' }}</dd></div><div><dt class="text-xs text-slate-500">Total (Karton/Kg)</dt><dd class="mt-1.5 font-semibold text-slate-900">{{ $realization->total_output !== null ? number_format($realization->total_output, 3, ',', '.') : 'Belum diisi' }} {{ $realization->unit_name_snapshot }}</dd></div></dl></x-card>
    <x-card><h2 class="text-base font-semibold text-slate-900">Report</h2><div class="mt-4 min-h-24 text-sm leading-6 text-slate-600 [&_a]:text-primary-600 [&_a]:underline [&_blockquote]:border-l-2 [&_blockquote]:border-line [&_blockquote]:pl-3 [&_blockquote]:text-slate-500 [&_ol]:mb-3 [&_ol]:list-decimal [&_ol]:pl-5 [&_p:last-child]:mb-0 [&_p]:mb-3 [&_ul]:mb-3 [&_ul]:list-disc [&_ul]:pl-5">{!! $realization->report ?: '<p class="text-slate-500">Tidak ada report untuk realisasi ini.</p>' !!}</div>{{-- Indikator complaint disembunyikan sementara atas permintaan. --}}</x-card>
</div>
@if(!$user->is_super_admin && $realization->status === 'assigned')
<x-card class="mt-5"><div class="mb-4"><h2 class="text-base font-semibold text-slate-900">Isi hasil pekerjaan</h2><p class="mt-1 text-sm text-slate-500">Semua field hasil pekerjaan bersifat opsional.</p></div><form data-realization-submit-form action="{{ route('realizations.update', $realization) }}" data-redirect="{{ route('realizations.show', $realization) }}" class="grid gap-4 sm:grid-cols-2"><input type="hidden" name="_method" value="PUT"><label class="grid gap-2 text-sm font-semibold"><span>Total (<span>{{ $realization->unit_name_snapshot }}</span>)</span><input type="number" step="0.001" min="0" name="total_output" class="h-11 rounded-lg border border-line px-3 font-normal"></label><label class="grid gap-2 text-sm font-semibold"><span>Waktu mulai</span><input type="time" name="start_time" class="h-11 rounded-lg border border-line px-3 font-normal"></label><label class="grid gap-2 text-sm font-semibold"><span>Waktu selesai</span><input type="time" name="end_time" class="h-11 rounded-lg border border-line px-3 font-normal"></label><label class="grid gap-2 text-sm font-semibold sm:col-span-2"><span>Report</span><textarea name="report" rows="4" placeholder="Tambahkan catatan hasil pekerjaan jika diperlukan" class="rounded-lg border border-line px-3 py-2 font-normal"></textarea></label><div class="flex justify-end sm:col-span-2"><button type="submit" class="inline-flex items-center gap-2 rounded-lg bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-primary-700"><x-icon name="check-circle" size="size-4" /> Kirim realisasi</button></div></form></x-card>
@endif
@if($user->is_super_admin)
<x-card id="assign-karyawan" class="mt-5"><div class="mb-4"><h2 class="text-base font-semibold text-slate-900">Assign ke karyawan</h2><p class="mt-1 text-sm text-slate-500">Pilih satu atau beberapa karyawan. Assignment ini opsional dan dapat dilakukan setelah realisasi disimpan.</p></div><form data-realization-assign-form action="{{ route('realizations.assign', $realization) }}" class="grid gap-4"><div class="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">@forelse($employees as $employee)<label class="flex items-center gap-3 rounded-lg border border-line px-3 py-2.5 text-sm"><input type="checkbox" name="employee_ids[]" value="{{ $employee->id }}" class="size-4 rounded border-line text-primary-600"><span><span class="block font-semibold text-slate-800">{{ $employee->full_name }}</span><span class="block text-xs text-slate-500">{{ $employee->employee_no }}</span></span></label>@empty<p class="text-sm text-slate-500">Belum ada karyawan aktif yang memiliki akun.</p>@endforelse</div>@if($employees->isNotEmpty())<div class="flex justify-end"><button type="submit" class="inline-flex items-center gap-2 rounded-lg bg-orange-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-orange-700"><x-icon name="users" size="size-4" /> Simpan assignment</button></div>@endif</form></x-card>
@endif
<x-card class="mt-5"><div class="mb-4 flex items-center justify-between"><h2 class="text-base font-semibold text-slate-900">Karyawan yang ditugaskan</h2><span class="rounded-full bg-primary-50 px-3 py-1 text-xs font-semibold text-primary-700">{{ $realization->employeeAssignments->count() }} orang</span></div>@if($realization->employeeAssignments->isEmpty())<p class="text-sm text-slate-500">Belum ada karyawan yang ditugaskan.</p>@else<div class="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">@foreach($realization->employeeAssignments as $assignment)<div class="flex items-center gap-3 rounded-lg border border-line bg-slate-50 px-3 py-2.5 transition hover:border-primary-200 hover:bg-primary-50/40"><span class="grid size-8 shrink-0 place-items-center rounded-full bg-primary-100 text-xs font-semibold text-primary-700 ring-2 ring-white">{{ mb_strtoupper(mb_substr($assignment->employee?->full_name ?? '?', 0, 1)) }}</span><div class="min-w-0"><p class="truncate text-sm font-semibold text-slate-800">{{ $assignment->employee?->full_name ?? '—' }}</p><p class="text-xs text-slate-500">{{ $assignment->employee?->employee_no ?? '—' }}</p></div></div>@endforeach</div>@endif</x-card>
</x-layouts.app>
