<x-layouts.app title="Potongan Gaji" active="deductions" :current-client="$currentClient" :user="$user">
    <div class="mb-6 flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-xs text-slate-500">Penggajian / Potongan Gaji</p><h1 class="mt-2 text-2xl font-semibold text-slate-950">Potongan Gaji</h1><p class="mt-1 text-sm text-slate-500">Kelola periode dan komponen potongan karyawan.</p></div><div class="flex flex-wrap items-center gap-2"><a href="{{ route('deductions.export') }}" class="inline-flex h-11 items-center gap-2 rounded-lg border border-orange-200 bg-orange-50 px-4 text-sm font-semibold text-orange-700 hover:bg-orange-100"><x-icon name="arrow-down-tray" size="size-4" /> Export</a><button type="button" data-deduction-import-open class="inline-flex h-11 items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-4 text-sm font-semibold text-emerald-700 hover:bg-emerald-100"><x-icon name="arrow-up-tray" size="size-4" /> Import</button><a href="{{ route('deductions.create') }}" class="inline-flex h-11 items-center gap-2 rounded-lg bg-primary-600 px-4 text-sm font-semibold text-white hover:bg-primary-700"><x-icon name="plus" size="size-4" /> Tambah potongan</a></div></div>
    <x-card :padding="false"><table data-server-table data-deduction-table class="w-full text-left text-sm"><thead><tr><th>Tanggal Input</th><th>Periode</th><th>SIM ID</th><th>Nama Lengkap</th><th>BPJS Kesehatan</th><th>BPJS Ketenagakerjaan</th><th>Koreksi Pengurangan</th><th>Koreksi Penambahan</th><th>Aksi</th></tr></thead><tbody></tbody></table></x-card>

    <div data-deduction-import-modal class="fixed inset-0 z-[90] hidden place-items-center overflow-y-auto bg-slate-950/40 p-4"><div class="my-4 w-full max-w-lg rounded-xl bg-white p-6 shadow-xl"><div class="mb-5 flex items-center justify-between"><div><h2 class="text-lg font-semibold text-slate-950">Import potongan gaji</h2><p class="mt-1 text-xs text-slate-500">Unggah file Excel sesuai format template.</p></div><button type="button" data-deduction-import-close class="rounded-lg p-2 text-slate-500 hover:bg-red-50 hover:text-red-600" aria-label="Tutup"><x-icon name="x-mark" /></button></div>
        <a href="{{ route('deductions.template') }}" class="flex items-center gap-3 rounded-xl border border-dashed border-line bg-slate-50 p-4 text-sm hover:bg-slate-100"><span class="grid size-10 shrink-0 place-items-center rounded-lg bg-primary-50 text-primary-600"><x-icon name="arrow-down-tray" size="size-5" /></span><span><span class="block font-semibold text-slate-900">Download template</span><span class="block text-xs text-slate-500">Isi data sesuai kolom pada template, lalu unggah kembali di bawah ini.</span></span></a>
        <form data-deduction-import-form class="mt-4 grid gap-4" action="{{ route('deductions.import') }}"><label class="grid gap-2 text-sm font-semibold"><span>File Excel <span class="text-danger">*</span></span><input type="file" name="file" accept=".xlsx,.xls" required class="rounded-lg border border-line px-3 py-2.5 text-sm font-normal file:mr-3 file:rounded-md file:border-0 file:bg-primary-50 file:px-3 file:py-1.5 file:text-xs file:font-semibold file:text-primary-700"></label><div class="flex justify-end gap-3 border-t border-line pt-4"><button type="button" data-deduction-import-close class="inline-flex items-center gap-2 rounded-lg border border-red-200 bg-red-50 px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-100"><x-icon name="x-mark" size="size-4" /> Batal</button><button type="submit" class="inline-flex items-center gap-2 rounded-lg bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-primary-700"><x-icon name="check-circle" size="size-4" /> Import</button></div></form>
    </div></div>

    <div data-deduction-row-modal class="fixed inset-0 z-[90] hidden place-items-center overflow-y-auto bg-slate-950/40 p-4"><div class="my-4 w-full max-w-2xl rounded-xl bg-white p-6 shadow-xl"><div class="mb-5 flex items-center justify-between"><div><h2 data-deduction-row-modal-title class="text-lg font-semibold text-slate-950">Edit potongan gaji</h2><p class="mt-1 text-xs text-slate-500">Perbarui komponen potongan untuk karyawan ini.</p></div><button type="button" data-deduction-row-close class="rounded-lg p-2 text-slate-500 hover:bg-red-50 hover:text-red-600" aria-label="Tutup"><x-icon name="x-mark" /></button></div>
        <form data-deduction-row-form class="grid gap-4"><input type="hidden" name="_method" value="PUT"><div class="grid gap-4 sm:grid-cols-2">
            @foreach ([['uniform_amount','Potongan seragam (Kaos/Celana)'],['equipment_amount','Potongan perlengkapan kerja'],['meal_amount','Potongan uang makan'],['correction_minus','Koreksi pengurangan'],['correction_plus','Koreksi penambahan']] as [$field,$label])<label class="grid gap-2 text-sm font-semibold"><span>{{ $label }}</span><x-rupiah-input :name="$field" placeholder="0" /></label>@endforeach
            <label class="grid gap-2 text-sm font-semibold"><span>BPJS Kesehatan (%)</span><input type="number" name="bpjs_health_percent" min="0" max="100" step="0.001" placeholder="Contoh: 1.000" class="h-11 rounded-lg border border-line px-3 font-normal"></label>
            <label class="grid gap-2 text-sm font-semibold"><span>BPJS Ketenagakerjaan (%)</span><input type="number" name="bpjs_employment_percent" min="0" max="100" step="0.001" placeholder="Contoh: 2.000" class="h-11 rounded-lg border border-line px-3 font-normal"></label>
            <div data-salary-advance-fields class="grid gap-4 sm:col-span-2 sm:grid-cols-2">
                <label class="grid gap-2 text-sm font-semibold"><span>Potongan DP Gaji</span><select name="salary_advance_type" class="h-11 rounded-lg border border-line bg-white px-3 font-normal"><option value="">Tidak ada</option><option value="fixed">Fixed (Rupiah)</option><option value="percentage">Persentase gaji borongan</option></select></label>
                <label data-salary-advance-value class="hidden grid gap-2 text-sm font-semibold"><span data-salary-advance-value-label>Nilai DP Gaji</span><div class="relative"><x-rupiah-input name="salary_advance_value" :decimals="3" placeholder="Masukkan nilai DP" data-salary-advance-value-input /><span data-salary-advance-suffix class="pointer-events-none absolute right-3.5 top-1/2 hidden -translate-y-1/2 text-sm font-medium text-slate-500">%</span></div></label>
            </div>
            <label class="grid gap-2 text-sm font-semibold sm:col-span-2"><span>Catatan</span><textarea name="notes" rows="2" placeholder="Catatan tambahan (opsional)" class="rounded-lg border border-line px-3 py-2 font-normal"></textarea></label>
        </div><div class="flex justify-end gap-3 border-t border-line pt-4"><button type="button" data-deduction-row-close class="inline-flex items-center gap-2 rounded-lg border border-red-200 bg-red-50 px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-100"><x-icon name="x-mark" size="size-4" /> Batal</button><button type="submit" class="inline-flex items-center gap-2 rounded-lg bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-primary-700"><x-icon name="check-circle" size="size-4" /> Simpan</button></div></form>
    </div></div>
</x-layouts.app>
