<x-layouts.app title="Master Produk" active="products" :current-client="$currentClient" :user="$user">
    <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div class="min-w-0"><p class="text-xs text-slate-500">Master Data / Produk</p><h1 class="mt-2 text-2xl font-semibold text-slate-950">Master Produk</h1><p class="mt-1 text-sm text-slate-500">Kelola produk dan tarif pekerjaan.</p></div><div class="flex flex-wrap items-center gap-2">
        <button type="button" data-product-create class="inline-flex h-11 w-full items-center justify-center gap-2 rounded-lg bg-primary-600 px-4 text-sm font-semibold text-white sm:w-auto"><x-icon name="plus" size="size-4"/> Tambah produk</button>
    </div></div>
    <x-card :padding="false"><div data-product-table-wrapper class="overflow-x-auto"><table data-server-table class="w-full min-w-[840px] text-left text-sm"><thead><tr><th>Client</th><th>Nama SKU</th><th>Nama produk</th><th>Satuan</th><th>Status</th><th>Aksi</th></tr></thead><tbody></tbody></table></div></x-card>
    <div data-product-modal class="fixed inset-0 z-[90] hidden place-items-center bg-slate-950/40 p-4"><div class="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-white p-6 shadow-xl"><div class="mb-5 flex items-center justify-between"><h2 data-product-modal-title class="text-lg font-semibold">Tambah produk</h2><button type="button" data-product-close><x-icon name="x-mark"/></button></div><form data-product-form class="grid gap-4"><input type="hidden" name="_method" value="POST"><div class="grid gap-4 sm:grid-cols-2">
        <label class="grid gap-2 text-sm font-semibold sm:col-span-2"><span>Client</span><select name="client_id" data-select2-select data-select2-remote="{{ route('clients.options') }}" data-select2-placeholder="Cari client..." class="w-full"><option value="{{ $currentClient->getKey() }}" selected>{{ $currentClient->code }} — {{ $currentClient->name }}</option></select></label>
        <label class="grid gap-2 text-sm font-semibold"><span>Nama SKU</span><input name="sku" type="text" placeholder="Contoh: SKU-0001" class="h-11 rounded-lg border border-line px-3 font-normal"></label>
        <label class="grid gap-2 text-sm font-semibold"><span>Nama produk</span><input name="name" type="text" placeholder="Masukkan nama produk" class="h-11 rounded-lg border border-line px-3 font-normal"></label>
        <label class="grid gap-2 text-sm font-semibold"><span>Satuan</span><select name="unit_id" data-tom-select data-tom-select-placeholder="Pilih satuan..." class="h-11 rounded-lg border border-line bg-white px-3 font-normal"><option value="">Pilih satuan...</option>@foreach($units as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></label>
        <label class="grid gap-2 text-sm font-semibold"><span>Group</span><select name="group_id" data-tom-select data-tom-select-placeholder="Pilih group..." class="h-11 rounded-lg border border-line bg-white px-3 font-normal"><option value="">Tanpa group</option>@foreach($groups as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></label>
        <label class="grid gap-2 text-sm font-semibold"><span>Cost center</span><select name="cost_center_id" data-tom-select data-tom-select-placeholder="Pilih cost center..." class="h-11 rounded-lg border border-line bg-white px-3 font-normal"><option value="">Tanpa cost center</option>@foreach($costCenters as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></label>
        <label class="grid gap-2 text-sm font-semibold"><span>Harga PO</span><x-rupiah-input name="po_price" :decimals="3" placeholder="15.000" /></label>
        <label class="grid gap-2 text-sm font-semibold"><span>Harga borongan karyawan</span><x-rupiah-input name="employee_rate" :decimals="3" placeholder="15.000" /></label>
        <label class="grid gap-2 text-sm font-semibold"><span>Estimasi output/jam</span><input name="estimated_output_per_hour" type="number" min="0" step="1" placeholder="Contoh: 120" class="h-11 rounded-lg border border-line px-3 font-normal"></label>
        <label class="grid gap-2 text-sm font-semibold sm:col-span-2"><span>Status produk</span><select name="status" class="h-11 rounded-lg border border-line bg-white px-3 font-normal"><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select></label>
    </div><div class="flex justify-end gap-3"><button type="button" data-product-close class="rounded-lg border border-line px-4 py-2.5 text-sm font-semibold">Batal</button><button type="submit" class="rounded-lg bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white">Simpan</button></div></form></div></div>

    <div data-product-detail-modal class="fixed inset-0 z-[90] hidden place-items-center bg-slate-950/40 p-4"><div class="max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-xl bg-white p-6 shadow-xl sm:p-8">
        <div class="mb-6 flex items-start justify-between gap-4"><div><h2 class="text-lg font-semibold text-slate-900">Detail produk</h2><p class="mt-1 text-sm text-slate-500">Informasi lengkap produk dan tarif pekerjaan.</p></div><button type="button" data-product-detail-close class="grid size-9 shrink-0 place-items-center rounded-lg text-slate-500 hover:bg-slate-50"><x-icon name="x-mark"/></button></div>
        <dl class="grid gap-x-8 gap-y-6 sm:grid-cols-2">
            <div class="rounded-xl border border-primary-100 bg-primary-50/60 p-4 sm:col-span-2">
                <div>
                    <dt class="text-xs font-medium uppercase tracking-wide text-primary-700">Client</dt>
                    <dd data-product-detail-client class="mt-1 text-base font-semibold text-slate-950">—</dd>
                </div>
                <div class="mt-4 grid gap-4 border-t border-primary-100 pt-4 sm:grid-cols-2">
                    <div><dt class="text-xs text-slate-500">Kode client</dt><dd data-product-detail-client-code class="mt-1 text-sm font-semibold text-slate-900">—</dd></div>
                    <div><dt class="text-xs text-slate-500">Status client</dt><dd data-product-detail-client-status class="mt-1">—</dd></div>
                </div>
            </div>
            <div><dt class="text-xs text-slate-500">Nama SKU</dt><dd data-product-detail-sku class="mt-1.5 text-sm font-semibold text-slate-900">—</dd></div>
            <div><dt class="text-xs text-slate-500">Nama produk</dt><dd data-product-detail-name class="mt-1.5 text-sm font-semibold text-slate-900">—</dd></div>
            <div><dt class="text-xs text-slate-500">Satuan</dt><dd data-product-detail-unit class="mt-1.5 text-sm font-semibold text-slate-900">—</dd></div>
            <div><dt class="text-xs text-slate-500">Group</dt><dd data-product-detail-group class="mt-1.5 text-sm font-semibold text-slate-900">—</dd></div>
            <div><dt class="text-xs text-slate-500">Cost center</dt><dd data-product-detail-cost-center class="mt-1.5 text-sm font-semibold text-slate-900">—</dd></div>
            <div><dt class="text-xs text-slate-500">Status produk</dt><dd data-product-detail-status class="mt-1.5">—</dd></div>
            <div><dt class="text-xs text-slate-500">Harga PO</dt><dd data-product-detail-po-price class="mt-1.5 text-sm font-semibold text-slate-900">—</dd></div>
            <div><dt class="text-xs text-slate-500">Estimasi output/jam</dt><dd data-product-detail-estimate class="mt-1.5 text-sm font-semibold text-slate-900">—</dd></div>
            <div><dt class="text-xs text-slate-500">Harga borongan karyawan</dt><dd data-product-detail-employee-rate class="mt-1.5 text-sm font-semibold text-slate-900">—</dd></div>
        </dl>
        <div class="mt-8 flex justify-end"><button type="button" data-product-detail-close class="rounded-lg border border-line px-4 py-2.5 text-sm font-semibold">Tutup</button></div>
    </div></div>

    {{-- Quick-manage: Satuan, Group, Cost center — reachable from the product form so Satuan/Group/Cost
    center never need a separate page visit. Each large modal lists existing records via datatable and
    reuses the same add/edit form + routes as the dedicated Master Data pages. --}}
    <div data-manage-modal="unit" class="fixed inset-0 z-[95] hidden items-center justify-center bg-slate-950/40 p-4"><div class="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-white p-6 shadow-xl sm:p-8">
        <div class="mb-5 flex items-start justify-between gap-4"><div><h2 class="text-lg font-semibold text-slate-950">Kelola satuan</h2><p class="mt-1 text-sm text-slate-500">Tambah, ubah, atau hapus satuan tanpa meninggalkan form produk.</p></div><button type="button" data-manage-modal-close class="grid size-9 shrink-0 place-items-center rounded-lg text-slate-500 hover:bg-slate-100"><x-icon name="x-mark"/></button></div>
        <div class="mb-4 flex justify-end"><button type="button" data-unit-create class="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-primary-600 px-4 text-sm font-semibold text-white hover:bg-primary-700"><x-icon name="plus" size="size-4"/> Tambah satuan</button></div>
        <div class="overflow-x-auto rounded-lg border border-line bg-white"><table data-server-table data-server-table-resource="units" data-search-placeholder="Cari kode atau nama satuan" data-empty-message="Belum ada satuan." class="w-full min-w-[520px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Kode</th><th class="px-5 py-3">Nama satuan</th><th class="px-5 py-3">Status</th><th class="px-5 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-line"></tbody></table></div>
    </div></div>

    <div data-manage-modal="group" class="fixed inset-0 z-[95] hidden items-center justify-center bg-slate-950/40 p-4"><div class="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-white p-6 shadow-xl sm:p-8">
        <div class="mb-5 flex items-start justify-between gap-4"><div><h2 class="text-lg font-semibold text-slate-950">Kelola group</h2><p class="mt-1 text-sm text-slate-500">Tambah, ubah, atau hapus group tanpa meninggalkan form produk.</p></div><button type="button" data-manage-modal-close class="grid size-9 shrink-0 place-items-center rounded-lg text-slate-500 hover:bg-slate-100"><x-icon name="x-mark"/></button></div>
        <div class="mb-4 flex justify-end"><button type="button" data-group-create class="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-primary-600 px-4 text-sm font-semibold text-white hover:bg-primary-700"><x-icon name="plus" size="size-4"/> Tambah group</button></div>
        <div class="overflow-x-auto rounded-lg border border-line bg-white"><table data-server-table data-server-table-resource="groups" data-search-placeholder="Cari kode atau nama group" data-empty-message="Belum ada group." class="w-full min-w-[520px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Kode</th><th class="px-5 py-3">Nama group</th><th class="px-5 py-3">Status</th><th class="px-5 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-line"></tbody></table></div>
    </div></div>

    <div data-manage-modal="cost-center" class="fixed inset-0 z-[95] hidden items-center justify-center bg-slate-950/40 p-4"><div class="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-white p-6 shadow-xl sm:p-8">
        <div class="mb-5 flex items-start justify-between gap-4"><div><h2 class="text-lg font-semibold text-slate-950">Kelola cost center</h2><p class="mt-1 text-sm text-slate-500">Tambah, ubah, atau hapus cost center tanpa meninggalkan form produk.</p></div><button type="button" data-manage-modal-close class="grid size-9 shrink-0 place-items-center rounded-lg text-slate-500 hover:bg-slate-100"><x-icon name="x-mark"/></button></div>
        <div class="mb-4 flex justify-end"><button type="button" data-cost-center-create class="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-primary-600 px-4 text-sm font-semibold text-white hover:bg-primary-700"><x-icon name="plus" size="size-4"/> Tambah cost center</button></div>
        <div class="overflow-x-auto rounded-lg border border-line bg-white"><table data-server-table data-server-table-resource="cost-centers" data-search-placeholder="Cari kode atau nama cost center" data-empty-message="Belum ada cost center." class="w-full min-w-[520px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Kode</th><th class="px-5 py-3">Nama cost center</th><th class="px-5 py-3">Status</th><th class="px-5 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-line"></tbody></table></div>
    </div></div>

    {{-- Nested add/edit forms (z-[100], above the z-[95] manage modals above) — same markup and JS wiring
    (data-unit-*/data-group-*/data-cost-center-*) as the dedicated Master Data pages. --}}
    <div data-unit-modal class="fixed inset-0 z-[100] hidden items-center justify-center bg-slate-950/40 p-4">
        <div class="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl">
            <div class="mb-5 flex items-center justify-between">
                <h2 data-unit-modal-title class="text-lg font-semibold text-slate-950">Tambah satuan</h2>
                <button type="button" data-unit-modal-close class="grid size-9 cursor-pointer place-items-center rounded-lg text-slate-500 hover:bg-slate-100 hover:text-ink"><x-icon name="x-mark" size="size-5" /></button>
            </div>
            <form data-unit-form action="{{ route('units.store') }}" class="grid gap-5">
                @csrf
                <div class="grid gap-5 sm:grid-cols-2">
                    <label class="grid gap-2 text-sm font-semibold text-slate-700"><span>Kode satuan <span class="text-danger">*</span></span><input name="code" required maxlength="30" placeholder="Contoh: PCS" class="h-11 rounded-lg border border-line px-3 font-normal outline-none focus:border-primary-600 focus:ring-3 focus:ring-primary-100"><span data-error-for="code" class="hidden text-xs font-normal text-danger"></span></label>
                    <label class="grid gap-2 text-sm font-semibold text-slate-700"><span>Nama satuan <span class="text-danger">*</span></span><input name="name" required maxlength="50" placeholder="Contoh: Pieces" class="h-11 rounded-lg border border-line px-3 font-normal outline-none focus:border-primary-600 focus:ring-3 focus:ring-primary-100"><span data-error-for="name" class="hidden text-xs font-normal text-danger"></span></label>
                </div>
                <label class="grid max-w-sm gap-2 text-sm font-semibold text-slate-700"><span>Status <span class="text-danger">*</span></span><select name="status" required class="h-11 rounded-lg border border-line bg-white px-3 font-normal outline-none focus:border-primary-600 focus:ring-3 focus:ring-primary-100"><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select><span data-error-for="status" class="hidden text-xs font-normal text-danger"></span></label>
                <div class="flex justify-end gap-3 border-t border-line pt-5">
                    <button type="button" data-unit-modal-close class="cursor-pointer rounded-lg border border-line px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-50">Batal</button>
                    <button type="submit" data-unit-submit class="inline-flex min-w-36 cursor-pointer items-center justify-center gap-2 rounded-lg bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-primary-700 disabled:cursor-wait disabled:opacity-70"><span data-unit-submit-label>Simpan satuan</span></button>
                </div>
            </form>
        </div>
    </div>

    <div data-group-modal class="fixed inset-0 z-[100] hidden place-items-center bg-slate-950/40 p-4"><div class="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl"><div class="mb-5 flex items-center justify-between"><h2 data-group-modal-title class="text-lg font-semibold">Tambah group</h2><button type="button" data-group-close><x-icon name="x-mark"/></button></div><form data-group-form class="grid gap-4"><input type="hidden" name="_method" value="POST"><label class="grid gap-2 text-sm font-semibold">Kode<input name="code" required class="h-11 rounded-lg border border-line px-3 font-normal"></label><label class="grid gap-2 text-sm font-semibold">Nama group<input name="name" required class="h-11 rounded-lg border border-line px-3 font-normal"></label><label class="grid gap-2 text-sm font-semibold">Status<select name="status" class="h-11 rounded-lg border border-line bg-white px-3 font-normal"><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select></label><div class="flex justify-end gap-3"><button type="button" data-group-close class="rounded-lg border border-line px-4 py-2.5 text-sm font-semibold">Batal</button><button class="rounded-lg bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white">Simpan</button></div></form></div></div>

    <div data-cost-center-modal class="fixed inset-0 z-[100] hidden place-items-center bg-slate-950/40 p-4"><div class="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl"><div class="mb-5 flex items-center justify-between"><h2 data-cost-center-modal-title class="text-lg font-semibold">Tambah cost center</h2><button type="button" data-cost-center-close aria-label="Tutup"><x-icon name="x-mark"/></button></div><form data-cost-center-form class="grid gap-4"><input type="hidden" name="_method" value="POST"><label class="grid gap-2 text-sm font-semibold"><span>Kode <span class="text-danger">*</span></span><input name="code" required placeholder="Contoh: OPS" class="h-11 rounded-lg border border-line px-3 font-normal"></label><label class="grid gap-2 text-sm font-semibold"><span>Nama cost center <span class="text-danger">*</span></span><input name="name" required placeholder="Contoh: Biaya Operasional" class="h-11 rounded-lg border border-line px-3 font-normal"></label><label class="grid gap-2 text-sm font-semibold"><span>Status <span class="text-danger">*</span></span><select name="status" required class="h-11 rounded-lg border border-line bg-white px-3 font-normal"><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select></label><div class="flex justify-end gap-3"><button type="button" data-cost-center-close class="rounded-lg border border-line px-4 py-2.5 text-sm font-semibold">Batal</button><button class="rounded-lg bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white">Simpan</button></div></form></div></div>
</x-layouts.app>
