<x-layouts.app title="Invoice Borongan" active="invoices" :current-client="$currentClient" :user="$user">
<div class="mb-6"><p class="text-xs text-slate-500">Pemborongan / Invoice</p><h1 class="mt-2 text-2xl font-semibold text-slate-950">Invoice Borongan</h1><p class="mt-1 text-sm text-slate-500">Rekap hasil realisasi untuk persiapan invoice. Nomor invoice sementara ditampilkan sebagai TBC.</p></div>
<x-card>
    <div data-invoice-filters class="grid min-w-0 gap-4 sm:grid-cols-2 xl:grid-cols-7 xl:items-end">
        <label class="grid min-w-0 gap-2 text-sm font-semibold">Periode<input data-invoice-period type="month" value="{{ $period }}" class="h-11 w-full min-w-0 rounded-lg border border-line px-3 font-normal outline-none focus:border-primary-600 focus:ring-3 focus:ring-primary-100"></label>
        <label class="grid min-w-0 gap-2 text-sm font-semibold">Shift<select data-invoice-shift class="h-11 w-full min-w-0 rounded-lg border border-line bg-white px-3 font-normal outline-none focus:border-primary-600 focus:ring-3 focus:ring-primary-100"><option value="">Semua shift</option>@foreach ($shifts as $shift)<option value="{{ $shift->id }}">{{ $shift->name }}</option>@endforeach</select></label>
        <label class="grid min-w-0 gap-2 text-sm font-semibold">Cost Center<select data-invoice-cost-center class="h-11 w-full min-w-0 rounded-lg border border-line bg-white px-3 font-normal outline-none focus:border-primary-600 focus:ring-3 focus:ring-primary-100"><option value="">Semua cost center</option>@foreach ($costCenters as $costCenter)<option value="{{ $costCenter->id }}">{{ $costCenter->name }}</option>@endforeach</select></label>
        <label class="grid min-w-0 gap-2 text-sm font-semibold">SKU<input data-invoice-sku type="search" placeholder="Cari SKU" class="h-11 w-full min-w-0 rounded-lg border border-line px-3 font-normal outline-none focus:border-primary-600 focus:ring-3 focus:ring-primary-100"></label>
        <label class="grid min-w-0 gap-2 text-sm font-semibold">Batch<input data-invoice-batch type="search" placeholder="Cari batch" class="h-11 w-full min-w-0 rounded-lg border border-line px-3 font-normal outline-none focus:border-primary-600 focus:ring-3 focus:ring-primary-100"></label>
        <div class="col-span-full flex min-w-0 items-end gap-2 xl:col-span-2"><button type="button" data-invoice-filter-submit class="inline-flex h-11 min-w-0 flex-1 items-center justify-center gap-2 whitespace-nowrap rounded-lg bg-primary-600 px-3 text-sm font-semibold text-white"><x-icon name="funnel" size="size-4"/> Terapkan</button><a data-invoice-export-excel href="{{ route('invoices.export.excel', ['period' => $period]) }}" class="inline-flex h-11 min-w-0 flex-1 items-center justify-center gap-2 whitespace-nowrap rounded-lg border border-emerald-200 bg-emerald-50 px-3 text-sm font-semibold text-emerald-700 hover:bg-emerald-100"><x-icon name="arrow-down-tray" size="size-4"/> Export</a></div>
    </div>
</x-card>
<x-card class="mt-5"><div class="max-w-full min-w-0 overflow-x-auto"><table data-server-table data-server-table-resource="invoices" data-search-placeholder="Cari invoice, SKU, batch..." class="w-full min-w-[1280px] table-fixed text-left text-sm"><thead><tr><th class="w-24">Invoice</th><th class="w-24">Periode</th><th class="w-32">Shift</th><th class="w-32">SKU</th><th class="w-36">Cost Center</th><th class="w-32">Batch</th><th class="w-24">Qty</th><th class="w-24">Satuan</th><th class="w-28">Man Power</th><th class="w-32">Harga PO</th><th class="w-36">Amount PO</th></tr></thead><tbody></tbody></table></div></x-card>
</x-layouts.app>
